# Generated by Django 5.0.4 on 2024-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('A', 'Agendado'), ('F', 'Finalizado'), ('C', 'Cancelado'), ('I', 'Iniciado')], default='A', max_length=1),
        ),
    ]
